config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update]
  resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :books, dependent: :destroy
   

    has_one_attached :profile_image
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top, :about]
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end


  protected

  def configure_permitted_parameters
    added_attrs = [:user_name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  before_action :ensure_correct_user, only:[:edit]
   def new
    @book = Book.new
   end


  # 投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = current_user

    #@books = @user.books.page(params[:page])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book.id)
    else
       render :edit
    end
  end

  def destroy
      @book = Book.find(params[:id])
      @book.destroy
    redirect_to books_path
  end


  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body, :img)
  end
def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  before_action :ensure_correct_user, only:[:edit]
  def new
    @book = Book.new
  end
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end
  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
    else
      render :index
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
    @user=User.find(params[:id])
    @user.update(user_params)
    render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<table class="table">
  <tbody>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</tbody>
</table>
<div class="row">
<%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog"></i>
<% end %>
</div>
<h2 class="mt-3">New book</h2>

<%= form_with model: books do |f| %>
<div class = "form-group">
<label for = "book_title">Title</label>
<%= f.text_field :title, class: 'form-control' %>
</div>
<div class = "form-group">
<label for = "book_opinion">Opinion</label>
<%= f.text_area :body, class: 'form-control' %>
</div>
<div class = "form-group">
<%= f.submit 'Create Book', :class=>"btn btn-success" %>
</div>
<% end %>

app/views/books/edit.html.erb
<main>
<p><% flash[:notice] %></p>
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<% if @book.errors.any? %>
<div id = "error_explanation">
  <h3><%= @book.errors.count %>error prohibited this book from being saved:</h3>
  <ul>
  <li>
  <% @book.errors.full_messages.each do |message| %>
  <%= message %>
  <li>
  <ui>
<% end %>
</div>
<% else %>
<% end %>

<%= form_with model: @book do |f| %>
  <div class="form-group">
  <label for="book_title">Title</label>
  <%= f.text_field :title, id:"inputtitle", class: 'form-control book_title' %>
  </div>
  <div class="form-group">
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body, id:"inputbody", class: 'form-control book_body' %>
  </div>
  <div class="form-group">
  <%= f.submit "Update Book", class: "btn btn-success" %>
  </div>
  <% end %>
  <%= link_to "Show", book_path(@book.id) %>
   |
  <%= link_to "Back", books_path %>
</div>
</div>
</div>
</main>

app/views/books/index.html.erb
<p><%= flash[:notice] %></p>
<div class="container px-5 px-sm-0">
<div id = "error_explanation">
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% else %>
<% end %>
</div>
    <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
    <%= image_tag @user.get_profile_image(100,100) %>
  <table class="table">
  <tbody>
  <tr>
	  <th>name</th>
	  <th><%= current_user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= current_user.introduction %></th>
  </tr>
</tbody>
</table>
<%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog"></i>
<% end %>
<h2 class="mt-3">New book</h2>

<%= form_with model: @book do |f| %>
<div class = "form-group">
<label for = "book_title">Title</label>
<%= f.text_field :title, class: 'form-control' %>
</div>
<div class = "form-group">
<label for = "book_opinion">Opinion</label>
<%= f.text_area :body, class: 'form-control' %>
</div>
<div class = "form-group">
<%= f.submit 'Create Book', :class=>"btn btn-success" %>
</div>
<% end %>
</div>
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">

<thead>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
  </tr>
</thead>
<tbody>
<% @books.each do |book| %>
 <tr>
  <td>
  <%= link_to user_path(book.user) do %>
  <%= image_tag book.user.get_profile_image(80,80) %>
  <% end %>
  </td>
  <td><%= link_to book.title, book_path(book.id)%></td>
  <td><%= book.body %></td>
 </tr>
<% end %>
</tbody>
</table>
</div>

</div>

</div>

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<main>
<p><%= flash[:notice] %></p>
<div class="container px-5 px-sm-0">
    <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
    <%= image_tag @book.user.get_profile_image(100,100) %>

<%= render 'list', books: @book_new, user: @book.user %>
    </div>
<div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
  <tbody>
      <tr>
        <td><%= link_to user_path(@book.user) do %>
          <%=  image_tag @book.user.get_profile_image(100,100) %>
          <br>
          <%= @book.user.name %>
          <% end %>
        </td>
        <td><%= link_to @book.title, book_path(@book.user.id)%></td>
        <td><%= @book.body %></td>
        <%- if @book.user.id == current_user.id %>
        <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success"  %></td>
        <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" %></td>
        <% else %>
        <td></td>
        <td></td>
      　<% end %>
      </tr>
  </tbody>
</table>
    </div>
   </div>
   </div>
  <main>

app/views/homes/about.html.erb
<body>
<p><%= flash[:notice] %></p>
<div class="container">
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<div class = "row">
<h1 class="px-3 mx-auto">Welcome to  <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
</div>
</div>
</div>
</body>

app/views/homes/top.html.erb
<main>
<p><%= flash[:notice] %></p>
<div class = "container">
<div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
        <%= link_to "Log in", user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in", method: :get %>
        </div>
        <div class="row">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up", method: :get %>
        </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class =  "container">
    <a class="navbar-brand" href="/">
      <span>Bookers</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
   <div class="collapse navbar-collapse" id="navbarNavDropdown">






    <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li>
      <%= link_to  user_path(current_user),class: "nav-link text-light" do %>
      <i class="fas fa-home"></i> Home
      <% end %>
      </li>
      <li>
      <%= link_to users_path, class: "nav-link text-light" do %>
      <i class="fas fa-users"></i> Users
      <% end %>
      </li>
      <li>
      <%= link_to books_path, class: "nav-link text-light" do %>
      <i class="fas fa-book-open"></i> Books
      <% end %>
      </li>
      <li>
      <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
      <i class="fas fa-sign-out-alt"></i> Log out
      <% end %>
      </li>
    <% else %>
      <li>
      <%= link_to root_path, class: "nav-link text-light" do %>
      <i class="fas fa-home"></i> Home
      <% end %>
      </li>
      <li>
      <%= link_to home_about_path, class: "nav-link text-light" do %>
      <i class="fas fa-link"></i> About
      <% end %>
      </li>
      <li>
      <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
      <i class="fas fa-user-plus"></i> Sign up
      <% end %>
      </li>
      <li>
      <%= link_to user_session_path, class: "nav-link text-light" do %>
      <i class="fas fa-sign-in-alt"></i> Log in
      <% end %>
      </li>
      </ui>
      </p>
    <% end %>
  </div>
  </nav>

  </header>


<%= yield %>
</div>




  <footer>
    <div class="container mt-5">
    	<div class="row">
      	<div class="mx-auto">
      		<p>CopyRight Infratop.inc</p>
      	</div>
      </div>
    </div>
  </footer>
  </body>

</html>

app/views/layouts/sidebar.erb
<div class="listings">
  <div class="listings_channels">
    <h2>User info</h2>
    <ul class="channel_list">
      <th>name</th>
      <th><%= user.name%></th>
      <th>introduction</th>
      <th><%= introduction%></th>
      <%= button_to <i class="fa-solid fa-user-gear"></i> ,edit_user_path %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<main>
<p><%= flash[:notice] %></p>
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<div id = "error_explanation">
<% if @user.errors.any? %>
  <h3><%= @user.errors.count %>error prohibited this book from being saved:</h3>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <ui>
<% end %>
<% else %>
<% end %>
</div>
<%= form_with model: @user do |f| %>
  <div class="form-group">
  <label for="inputName">Name</label>
  <%= f.text_field :name, id:"name", class: 'form-control' %>
  </div>
  <div class="form-group">
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*", class: 'form-control-file user_image' %>
  </div>
  <div class="form-group">
  <label for="introduction">Introduction</label>
  <%= f.text_area :introduction, id:"user_introduction", class: 'form-control introduction' %>
  </div>
  <div class="form-group">
  <%= f.submit "Update User", class: "btn btn-secondary" %>
  </div>
<% end %>
</div>
</div>
</div>
</main>

app/views/users/index.html.erb
<body>
<main>
<p><%= flash[:notice] %></p>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<h2>User info</h2>
<%= image_tag @user.get_profile_image(100,100) %>
<%= render 'books/list', books: @book, user: @user %>
</div>
<div class="col-md-8 offset-md-1">
<h2>Users</h2>
<table class = "table">

<thead>
  <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
  </tr>
</thead>

<tbody>
<% @users.each do |user| %>
 <tr>
  <td><%= image_tag user.get_profile_image(80,80) %>
  </td>
  <td><%= user.name %></td>
  <td><%= link_to "Show", user_path(user.id) %></td>
 </tr>
<% end %>
</tbody>
</table>


</div>
</div>
</div>
</main>
</body>

app/views/users/show.html.erb
<p><%= flash[:notice] %></p>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<h2>User info</h2>
<%= image_tag @user.get_profile_image(100,100) %>

<%= render 'books/list', books: @book, user: @user %>
</div>
<!-- ユーザーの投稿一覧 -->

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">



<thead>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
  </tr>
</thead>
<tbody>
<% @books.each do |book| %>
 <tr>
  <td><%= link_to user_path do %>
  <%= image_tag book.user.get_profile_image(80,80) %>
  <% end %>
  </td>
  <td><%= link_to book.title, book_path(book.id)%></td>
  <td><%= book.body %></td>
 </tr>
<% end %>
</tbody>
</table>
</div>

</div>

</div>